export type RootStackParamList = {
  Login: undefined;
  Signup: undefined;
  PrivacyPolicy: undefined;
  TermsOfUse: undefined;
  ForgotPassword: undefined;
  ResetPassword: { token?: string } | undefined;
  PrivacyAcceptance: undefined;
  TermsAcceptance: undefined;
  AccountPrivacy: undefined;
  AccountDeletion: undefined;
  OwnerHome: undefined;
  OwnerProfile: undefined;
  OwnerProfileEdit: undefined;
  OwnerContractTemplate: undefined;
  OwnerVehicles: undefined;
  VehicleHighlight: { vehicleId: string };
  OwnerPartners: undefined;
  VehicleForm: { vehicleId?: string };
  VehiclePhotos: { vehicleId: string };
  OwnerPendingDrivers: undefined;
  OwnerDriverProfile: { driverUserId: string };
  OwnerRentals: undefined;
  OwnerRentalDetail: { rentalId: string };
  RentalInstructions: { rentalId: string; contractTextDraft?: string };
  RentalContractEdit: { rentalId: string; initialContractText: string };
  RentalInspectionForm: { rentalId: string; type: "CHECKOUT" | "CHECKIN" };
  DriverHome: undefined;
  DriverPreRegister: undefined;
  DriverStatus: undefined;
  DriverRentals: undefined;
  Marketplace: undefined;
  VehicleDetail: { vehicleId: string };
  UserReviews: {
    targetUserId: string;
    targetRole: "OWNER" | "DRIVER";
    title: string;
    displayName?: string | null;
  };
  RentalDetail: { rentalId: string };
  AdminHub: undefined;
  AdminCampaigns: undefined;
  AdminHighlights: undefined;
  AdminCampaignForm: { campaignId?: string };
  AdminOwners: undefined;
  AdminOwnerDetail: { ownerUserId: string };
  AdminOwnerVehicleDetail: { vehicleId: string };
  AdminRentals: undefined;
  AdminPendingRentals: undefined;
  AdminRentalDetail: { rentalId: string };
};
