export type RootStackParamList = {
  Login: undefined;
  Signup: undefined;
  PrivacyPolicy: undefined;
  ForgotPassword: undefined;
  ResetPassword: { token?: string } | undefined;
  PrivacyAcceptance: undefined;
  AccountPrivacy: undefined;
  AccountDeletion: undefined;
  OwnerHome: undefined;
  OwnerProfile: undefined;
  OwnerProfileEdit: undefined;
  OwnerContractTemplate: undefined;
  OwnerVehicles: undefined;
  OwnerPartners: undefined;
  VehicleForm: { vehicleId?: string };
  VehiclePhotos: { vehicleId: string };
  OwnerPendingDrivers: undefined;
  OwnerDriverProfile: { driverUserId: string };
  OwnerRentals: undefined;
  OwnerRentalDetail: { rentalId: string };
  RentalInstructions: { rentalId: string; contractTextDraft?: string };
  RentalContractEdit: { rentalId: string; initialContractText: string };
  RentalInspectionForm: { rentalId: string; type: "CHECKOUT" | "CHECKIN" };
  DriverHome: undefined;
  DriverPreRegister: undefined;
  DriverStatus: undefined;
  DriverRentals: undefined;
  Marketplace: undefined;
  VehicleDetail: { vehicleId: string };
  RentalDetail: { rentalId: string };
};
