-- Bloqueia acesso via API REST do Supabase (anon/authenticated) sem políticas.
-- O backend Prisma (postgres) não é afetado.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Partner" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OwnerProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DriverProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Vehicle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MarketplaceExposureEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HighlightPlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HighlightPlatformConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VehicleHighlightOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VehicleDriverBlock" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VehiclePhoto" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Rental" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalFinancialSummary" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalFinancialEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalInspection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalInspectionPhoto" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalReview" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PasswordResetToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AdCampaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AdEvent" ENABLE ROW LEVEL SECURITY;
